export enum AgentNames {
"Clay_PC_C" = "Raze",
"Pandemic_PC_C" = "Viper",
"Wraith_PC_C" = "Omen",
"Hunter_PC_C" = "Sova",
"Thorne_PC_C" = "Sage",
"Phoenix_PC_C" = "Phoenix",
"Wushu_PC_C" = "Jett",
"Gumshoe_PC_C" = "Cypher",
"Sarge_PC_C" = "Brimstone",
"Breach_PC_C" = "Breach",
"Vampire_PC_C" = "Reyna",
"Killjoy_PC_C" = "Killjoy",
"Guide_PC_C" = "Skye",
"Stealth_PC_C" = "Yoru",
"Rift_PC_C" = "Astra",
"Grenadier_PC_C" = "KAY/O",
"Deadeye_PC_C" = "Chamber",
"Sprinter_PC_C" = "Neon",
"BountyHunter_PC_C" = "Fade",
"Mage_PC_C" = "Harbor",
"AggroBot_PC_C" = "Gekko",
"Cable_PC_C" = "Deadlock",
"Sequoia_PC_C" = "Iso"
}