export enum WeaponNames {
    TX_Hud_Pistol_Classic = "Classic",
    TX_Hud_Pistol_Slim = "Shorty",
    TX_Hud_Pistol_AutoPistol = "Frenzy",
    TX_Hud_Pistol_Luger = "Ghost",
    TX_Hud_Pistol_Sheriff = "Sheriff",
    TX_Hud_Shotguns_Pump = "Bucky",
    TX_Hud_Shotguns_Persuader = "Judge",
    TX_Hud_SMGs_Vector = "Stinger",
    TX_Hud_SMGs_Ninja = "Spectre",
    TX_Hud_Rifles_Burst = "Bulldog",
    TX_Hud_Rifles_DMR = "Guardian",
    TX_Hud_Rifles_Ghost = "Phantom",
    TX_Hud_Rifles_Volcano = "Vandal",
    TX_Hud_Sniper_Bolt = "Marshal",
    TX_Hud_Sniper_Operater = "Operator",
    TX_Hud_Sniper_DoubleSniper = "Outlaw",
    TX_Hud_LMG = "Ares",
    TX_Hud_HMG = "Odin",
    knife = "Knife",
    TX_Hud_Bomb_S = "Bomb"
}